@Backend_HostAddress = https://localhost:53800
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IlNTaWRuZXkiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJzaWRuZXlsZWUyMDE4QGdtYWlsLmNvbSIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkN1c3RvbWVyIiwiZXhwIjoxNzQwNDg1NjY5LCJpc3MiOiJSZUNsb3NldElzc3VlciIsImF1ZCI6IlJlQ2xvc2V0VXNlcnMifQ.CoRNLe-XawKvBokjzd35--LGNDiRl8dyOLPqfQAeHxc
###

GET {{Backend_HostAddress}}/checkout

###

POST {{Backend_HostAddress}}/checkout
Content-Type: application/json
Authorization: Bearer {{token}}
{
  "DeliveryOption": 1,
  "PaymentId": 1,
  "OrderItems": [
    {
      "ProductId": 1,
      "Quantity": 2,
      "itemPrice": 50.00 
    },
    {
      "ProductId": 2,
      "Quantity": 1,
      "itemPrice": 30.00
    }
  ]
}


###


DELETE {{Backend_HostAddress}}/checkout/1

###

GET {{Backend_HostAddress}}/checkout/1
Authorization: Bearer {{token}}
###

PUT {{Backend_HostAddress}}/checkout/1
Content-Type: application/json
Authorization: Bearer {{token}}
{
  //UpdateOrderRequestDto
}

###

GET {{Backend_HostAddress}}/orderitem

###

POST {{Backend_HostAddress}}/orderitem
Content-Type: application/json

{
  "OrderItem_Id": 1,
  "Order_Id": 1,
  "Product_Id": 1,
  "Quantity": 2,
  "Price": 50
}

###

DELETE {{Backend_HostAddress}}/orderitem/1

###

GET {{Backend_HostAddress}}/orderitem/1

###

PUT {{Backend_HostAddress}}/orderitem/1
Content-Type: application/json

{
  "OrderItem_Id": 1,
  "Order_Id": 1,
  "Product_Id": 1,
  "Quantity": 3,
  "Price": 75
}

###


GET {{Backend_HostAddress}}/payment
Authorization: Bearer {{token}}
###

POST {{Backend_HostAddress}}/payment
Content-Type: application/json
Authorization: Bearer {{token}}
{
  "Payment_Id": 1,
  "Amount": 100,
  "Payment_Date": "2023-10-01T10:00:00",
  "PaymentMethod": "CreditCard",
  "CardNumber": "1234567812345678",
  "CVV": "123",
  "BillingZip": "123456",
  "BillingAddress": "123 Main St, Anytown, USA"
}

###

DELETE {{Backend_HostAddress}}/payment/1

###

GET {{Backend_HostAddress}}/payment/1
Authorization: Bearer {{token}}
###

PUT {{Backend_HostAddress}}/payment/1
Content-Type: application/json
Authorization: Bearer {{token}}
{
  "Payment_Id": 1,
  "Order_Id": 1,
  "Amount": 150,
  "Payment_Date": "2023-10-02T10:00:00",
  "Payment_Method": "PayPal"
}

###



POST {{Backend_HostAddress}}/admin/register
Content-Type: application/json

{
  "Username":"adminTwo",
  "Email":"admin2@email.com",
  "Password":"password1!"
}

###

POST {{Backend_HostAddress}}/admin/login
Content-Type: application/json

{
  "Email":"admin2@email.com",
  "Password":"password1!"
}

###

GET {{Backend_HostAddress}}/admin/auth

###

@id=0
PUT {{Backend_HostAddress}}/admin/update/{{id}}
Content-Type: application/json

{
  //UpdateAdminRequest
}

###

DELETE {{Backend_HostAddress}}/admin/delete/{{id}}

###

POST {{Backend_HostAddress}}/user/register
Content-Type: application/json

{
  "Email":"admin2@email.com",
  "Username":"adminTwo",
  "Password":"password1!"
}

###

POST {{Backend_HostAddress}}/user/login
Content-Type: application/json

{
  "UsernameOrEmail":"sidneylee2018@gmail.com",
  "Password":"password1!"
}

###

GET {{Backend_HostAddress}}/user/auth

###

PUT {{Backend_HostAddress}}/user/update/{{id}}
Content-Type: application/json

{
  //UpdateUserRequest
}

###

DELETE {{Backend_HostAddress}}/user/delete/{{id}}

###

POST {{Backend_HostAddress}}/user/register
Content-Type: application/json

{
  "Email":"jeraldliu@gmail.com",
  "Username":"Jerald",
  "Password":"P@ssw0rd!"
}

###

POST {{Backend_HostAddress}}/api/product
Content-Type: application/json

{
 
  
    "Name": "Warm Wool Sweater",
    "Image": "https://example.com/images/sweater.jpg",
    "Description": "A cozy wool sweater designed for warmth and comfort.",
    "SustainabilityNotes": "Made from ethically sourced wool.",
    "SizingChart": "https://example.com/sizing-chart/sweater",
    "Price": 49.99,
    "Quality": true,
    "Brand": "GreenThreads",
    "Available": true,
    "CategoryId": 2,
    "WarehouseId": 1

}

###

GET {{Backend_HostAddress}}/OrderItem/graph

###

GET {{Backend_HostAddress}}/orderitem/list

###

PUT {{Backend_HostAddress}}/payment/1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "DefaultPreference" : Active
}

###

POST {{Backend_HostAddress}}/voucher/1/claim
Content-Type: application/json
Authorization: Bearer {{token}}
{
}

###

PUT {{Backend_HostAddress}}/user/update/2/123
Content-Type: application/json
Authorization: Bearer {{token}}
{

}

###

GET {{Backend_HostAddress}}/voucher/claimed
Content-Type: application/json
Authorization: Bearer {{token}}
{

}